In [4]:
# Import libraries
import pandas as pd
import numpy as np

# Load datasets
sales = pd.read_csv("sales_orders_integrated.csv")
purchase = pd.read_csv("purchase_orders_integrated.csv")
stock = pd.read_csv("stock_inventory_integrated.csv")

# Display dataset dimensions
print("Sales dataset:", sales.shape)
print("Purchase dataset:", purchase.shape)
print("Stock dataset:", purchase.shape)

Sales dataset: (130402, 47)
Purchase dataset: (155495, 68)
Stock dataset: (155495, 68)

In [6]:
# Preview datasets
display(sales.head())
display(purchase.head())
display(stock.head())

,so_id,customer_id,branch_id,order_date,delivery_date,order_status,payment_terms,total_order_value,total_gst_amount,grand_total,...,warehouse_type,warehouse_capacity,service_center_available,manager_id,total_employees,avg_monthly_revenue,monthly_operational_cost,market_demand_index,warehouse_capacity_sqft,line_sales_value
0,SO-990591,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,...,Service Hub,34120 sqft,Yes,4772,63,3245890,2018000,7,34120,214700
1,SO-990591,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,...,Service Hub,34120 sqft,Yes,4772,63,3245890,2018000,7,34120,620
2,SO-990591,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,...,Service Hub,34120 sqft,Yes,4772,63,3245890,2018000,7,34120,930
3,SO-990591,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,...,Service Hub,34120 sqft,Yes,4772,63,3245890,2018000,7,34120,13050
4,SO-990591,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,...,Service Hub,34120 sqft,Yes,4772,63,3245890,2018000,7,34120,119400

,po_id,supplier_id,branch_id,order_date,expected_delivery_date,received_date,po_status,total_cost,total_gst_amount,grand_total,...,manager_id,total_employees,avg_monthly_revenue,monthly_operational_cost,market_demand_index,warehouse_capacity_sqft,delivery_delay_days,delivery_status,line_purchase_value,expected_lead_days
0,PO-141186,SUP0001,PUN001,2019-04-10,2019-04-29,2019-04-29,Received,22955232.11,6.427465e+06,2.938270e+07,...,6114,74,4389120,2654000,8,38750,0.0,On Time,8122032.36,19
1,PO-141186,SUP0001,PUN001,2019-04-10,2019-04-29,2019-04-29,Received,22955232.11,6.427465e+06,2.938270e+07,...,6114,74,4389120,2654000,8,38750,0.0,On Time,973109.36,19
2,PO-141186,SUP0001,PUN001,2019-04-10,2019-04-29,2019-04-29,Received,22955232.11,6.427465e+06,2.938270e+07,...,6114,74,4389120,2654000,8,38750,0.0,On Time,636660.70,19
3,PO-141186,SUP0001,PUN001,2019-04-10,2019-04-29,2019-04-29,Received,22955232.11,6.427465e+06,2.938270e+07,...,6114,74,4389120,2654000,8,38750,0.0,On Time,4977604.13,19
4,PO-141186,SUP0001,PUN001,2019-04-10,2019-04-29,2019-04-29,Received,22955232.11,6.427465e+06,2.938270e+07,...,6114,74,4389120,2654000,8,38750,0.0,On Time,8245825.56,19

,movement_id,product_id,branch_id,movement_type,movement_date,quantity,reference_type,reference_id,running_balance,opening_stock,...,warehouse_capacity,service_center_available,manager_id,total_employees,avg_monthly_revenue,monthly_operational_cost,market_demand_index,warehouse_capacity_sqft,stock_gap,stock_status
0,MOV-OUT-184742,P001,AHM001,OUT,2019-01-03,8,SO,SO-157767,228,236,...,34120 sqft,Yes,4772,63,3245890,2018000,7,34120,106637,At/Above Reorder Level
1,MOV-OUT-208422,P001,AHM001,OUT,2019-01-05,12,SO,SO-168735,216,236,...,34120 sqft,Yes,4772,63,3245890,2018000,7,34120,106637,At/Above Reorder Level
2,MOV-IN-111128,P001,AHM001,IN,2019-01-23,174,PO,PO-181094,390,236,...,34120 sqft,Yes,4772,63,3245890,2018000,7,34120,106637,At/Above Reorder Level
3,MOV-OUT-159140,P001,AHM001,OUT,2019-01-25,12,SO,SO-947377,378,236,...,34120 sqft,Yes,4772,63,3245890,2018000,7,34120,106637,At/Above Reorder Level
4,MOV-OUT-173693,P001,AHM001,OUT,2019-01-25,11,SO,SO-879896,367,236,...,34120 sqft,Yes,4772,63,3245890,2018000,7,34120,106637,At/Above Reorder Level

In [7]:
# Check missing values
print("Sales missing values:")
display(sales.isnull().sum()[sales.isnull().sum() > 0])

print("Purchase missing values:")
display(purchase.isnull().sum()[purchase.isnull().sum() > 0])

print("Stock missing values:")
display(stock.isnull().sum()[stock.isnull().sum() > 0])

Sales missing values:

Series([], dtype: int64)

Purchase missing values:

received_date          15418
delivery_delay_days    15418
dtype: int64

Stock missing values:

Series([], dtype: int64)

In [11]:
# Total Sales Revenue

total_sales = sales["line_sales_value"].sum()

print(total_sales)

25447392560

In [24]:
# Total Units Sold

total_units = sales["quantity"].sum()

print(total_units)

1368534

In [25]:
# Total Sales Orders

total_orders = sales["so_id"].nunique()

print(total_orders)

20000

In [26]:
# Average Order Value

average_order_value = total_sales / total_orders

print(average_order_value)

1272369.628

In [27]:
kpi_results = pd.DataFrame({
    "KPI": [
        "Total Sales Revenue",
        "Total Units Sold",
        "Total Sales Orders",
        "Average Order Value"
    ],
    "Value": [
        total_sales,
        total_units,
        total_orders,
        average_order_value
    ]
})

kpi_results

                   KPI         Value
0  Total Sales Revenue  2.544739e+10
1     Total Units Sold  1.368534e+06
2   Total Sales Orders  2.000000e+04
3  Average Order Value  1.272370e+06

In [28]:
#Procurement Spend

total_procurement_spend = purchase["line_purchase_value"].sum()

print(total_procurement_spend)

346621977539.14

In [29]:
#Units Purchased

total_procurement_spend = purchase["line_purchase_value"].sum()

print(total_procurement_spend)

346621977539.14

In [30]:
#Number of purchase orders

total_purchase_orders = purchase["po_id"].nunique()

print(total_purchase_orders)

24000

In [31]:
#Average PO Value

average_po_value = (
    total_procurement_spend / total_purchase_orders
)

print(average_po_value)

14442582.397464167

In [32]:
#Supplier Analysis

supplier_spend = (
    purchase.groupby("supplier_name")["line_purchase_value"]
    .sum()
    .sort_values(ascending=False)
)

supplier_spend

supplier_name
Tianjin OEM Supplies               4.474850e+10
Shenzhen OEM Supplies              4.366427e+10
Shanghai Distributor Supplies      4.365799e+10
Suzhou Local Vendor Supplies       4.363241e+10
Hangzhou OEM Supplies              4.343271e+10
Qingdao Distributor Supplies       4.324373e+10
Ningbo Distributor Supplies        4.242755e+10
Guangzhou Local Vendor Supplies    4.181482e+10
Name: line_purchase_value, dtype: float64

In [2]:
import pandas as pd
import numpy as np

In [6]:
sales = pd.read_csv("sales_orders_integrated.csv")
purchase = pd.read_csv("purchase_orders_integrated.csv")
inventory = pd.read_csv("stock_inventory_integrated.csv")
products = pd.read_csv("products.csv")

In [7]:
print(sales.shape)
print(purchase.shape)
print(inventory.shape)
print(products.shape)

(130402, 47)
(155495, 68)
(237230, 52)
(30, 23)

In [20]:
sales_product = sales.merge(
    products[["product_id", "product_name", "category"]],
    on="product_id",
    how="left"
)

In [21]:
product_sales = (
    sales_product.groupby("product_name")["line_sales_value"]
    .sum()
    .sort_values(ascending=False)
)

product_units = (
    sales_product.groupby("product_name")["quantity"]
    .sum()
    .sort_values(ascending=False)
)
print(product_sales,
     product_units)

product_name
Engine Block EB-600             5381418000
Transmission Assembly TA-800    3760422500
Boom Cylinder BC-400            2142016800
Swing Motor SWM-350             1829645800
Track Chain TC-45               1813885000
Turbocharger TB-900             1639043600
Hydraulic Cylinder HC-200       1286491200
Hydraulic Pump HP-300           1112030500
Fuel Pump FP-350                1005144300
Control Valve CV-75              774341100
Starter Motor SM-700             669695400
Idler Wheel IW-55                575459150
Alternator ALT-500               523387200
Wheel Rim WR-24                  508805100
Radiator RD-250                  472321200
Track Roller TR-60               453426600
Fuel Injector FI-220             380469700
Cabin Glass CG-20                357944300
Pressure Sensor PS-90            185910700
Brake Pad BP-40                  112631400
Light Assembly LA-18             103869000
Hydraulic Hose HH-60              67378600
Seal Kit SK-15                    63917450
Air Filter AF-120                 57105000
Pivot Pin PP-12                   52141000
Engine Oil Filter OF-90           32646240
Bucket Tooth BT-10                26318080
Fan Belt FB-30                    23700560
O-Ring Set OR-50                  21925440
Grease Cartridge GC-5             13901640
Name: line_sales_value, dtype: int64 product_name
Pressure Sensor PS-90           47066
Turbocharger TB-900             46964
Alternator ALT-500              46731
Hydraulic Cylinder HC-200       46612
Hydraulic Hose HH-60            46468
Boom Cylinder BC-400            46364
Radiator RD-250                 46306
Light Assembly LA-18            46164
Brake Pad BP-40                 45972
Swing Motor SWM-350             45971
Fuel Pump FP-350                45897
Control Valve CV-75             45819
Air Filter AF-120               45684
O-Ring Set OR-50                45678
Cabin Glass CG-20               45598
Fan Belt FB-30                  45578
Track Chain TC-45               45575
Hydraulic Pump HP-300           45389
Bucket Tooth BT-10              45376
Engine Oil Filter OF-90         45342
Pivot Pin PP-12                 45340
Engine Block EB-600             45222
Transmission Assembly TA-800    45035
Wheel Rim WR-24                 45027
Fuel Injector FI-220            45026
Starter Motor SM-700            44946
Grease Cartridge GC-5           44844
Idler Wheel IW-55               44437
Seal Kit SK-15                  44081
Track Roller TR-60              44022
Name: quantity, dtype: int64

In [22]:
product_order_frequency = (
    sales_product.groupby("product_name")["so_id"]
    .nunique()
    .sort_values(ascending=False)
)
print(product_order_frequency)

product_name
Hydraulic Cylinder HC-200       3982
Alternator ALT-500              3936
Radiator RD-250                 3934
Turbocharger TB-900             3933
Light Assembly LA-18            3917
Fan Belt FB-30                  3913
Hydraulic Hose HH-60            3906
Air Filter AF-120               3895
Control Valve CV-75             3892
Brake Pad BP-40                 3883
Pressure Sensor PS-90           3882
Boom Cylinder BC-400            3873
Engine Oil Filter OF-90         3861
Bucket Tooth BT-10              3860
O-Ring Set OR-50                3860
Fuel Pump FP-350                3856
Hydraulic Pump HP-300           3854
Cabin Glass CG-20               3853
Swing Motor SWM-350             3849
Fuel Injector FI-220            3840
Wheel Rim WR-24                 3839
Transmission Assembly TA-800    3838
Grease Cartridge GC-5           3823
Pivot Pin PP-12                 3823
Starter Motor SM-700            3784
Seal Kit SK-15                  3783
Track Chain TC-45               3781
Engine Block EB-600             3773
Track Roller TR-60              3762
Idler Wheel IW-55               3754
Name: so_id, dtype: int64

In [23]:
product_sales = (
    sales_product.groupby("product_name")["line_sales_value"]
    .sum()
    .sort_values(ascending=False)
)
print(product_sales)

product_name
Engine Block EB-600             5381418000
Transmission Assembly TA-800    3760422500
Boom Cylinder BC-400            2142016800
Swing Motor SWM-350             1829645800
Track Chain TC-45               1813885000
Turbocharger TB-900             1639043600
Hydraulic Cylinder HC-200       1286491200
Hydraulic Pump HP-300           1112030500
Fuel Pump FP-350                1005144300
Control Valve CV-75              774341100
Starter Motor SM-700             669695400
Idler Wheel IW-55                575459150
Alternator ALT-500               523387200
Wheel Rim WR-24                  508805100
Radiator RD-250                  472321200
Track Roller TR-60               453426600
Fuel Injector FI-220             380469700
Cabin Glass CG-20                357944300
Pressure Sensor PS-90            185910700
Brake Pad BP-40                  112631400
Light Assembly LA-18             103869000
Hydraulic Hose HH-60              67378600
Seal Kit SK-15                    63917450
Air Filter AF-120                 57105000
Pivot Pin PP-12                   52141000
Engine Oil Filter OF-90           32646240
Bucket Tooth BT-10                26318080
Fan Belt FB-30                    23700560
O-Ring Set OR-50                  21925440
Grease Cartridge GC-5             13901640
Name: line_sales_value, dtype: int64

In [24]:
product_units = (
    sales_product.groupby("product_name")["quantity"]
    .sum()
    .sort_values(ascending=False)
)
print(product_units)

product_name
Pressure Sensor PS-90           47066
Turbocharger TB-900             46964
Alternator ALT-500              46731
Hydraulic Cylinder HC-200       46612
Hydraulic Hose HH-60            46468
Boom Cylinder BC-400            46364
Radiator RD-250                 46306
Light Assembly LA-18            46164
Brake Pad BP-40                 45972
Swing Motor SWM-350             45971
Fuel Pump FP-350                45897
Control Valve CV-75             45819
Air Filter AF-120               45684
O-Ring Set OR-50                45678
Cabin Glass CG-20               45598
Fan Belt FB-30                  45578
Track Chain TC-45               45575
Hydraulic Pump HP-300           45389
Bucket Tooth BT-10              45376
Engine Oil Filter OF-90         45342
Pivot Pin PP-12                 45340
Engine Block EB-600             45222
Transmission Assembly TA-800    45035
Wheel Rim WR-24                 45027
Fuel Injector FI-220            45026
Starter Motor SM-700            44946
Grease Cartridge GC-5           44844
Idler Wheel IW-55               44437
Seal Kit SK-15                  44081
Track Roller TR-60              44022
Name: quantity, dtype: int64

In [25]:
#Branch Analysis

branch_sales = (
    sales.groupby("branch_name")["line_sales_value"]
    .sum()
    .sort_values(ascending=False)
)
print(branch_sales)

branch_name
Chennai South Hub      5192125100
Kolkata East Depot     4787656160
Ahmedabad West Hub     4407886140
Delhi Central          3865954470
Pune Distribution      3741098180
Hyderabad Logistics    3452672510
Name: line_sales_value, dtype: int64

In [37]:
#Supplier Delivery Analysis

purchase["delivery_status"].value_counts()

average_delay = purchase["delivery_delay_days"].mean()

print(average_delay)

0.5088843992946737